import 'package:flutter/material.dart';
import 'package:lucide_icons_flutter/lucide_icons.dart';
import 'package:super_app/l10n/locale_controller.dart';

/// Asosiy ekrandagi katakchalar va yangi qo'shimcha xizmatlar bilan mos
/// keladigan barcha xizmat turlari.
enum ServiceHubKind {
  sartarosh,
  salon,
  futbol,
  ishchi,
  usta,
  elektrik,
  santexnik,
  tozalash,
  avtoYordam,
  konditsioner,
  enaga,
  repetitor,
  // 6 ta YANGI:
  dezinfeksiya,
  texnikaUstasi,
  kuryerlik,
  massajHijoma,
  hamshira,
  stomatologiya,
  tadbirlar,
  bozorchi,
  oshxona,
  gameZona,
  sportMaydon,
  kompUsta,
  boshqa,
  yana,
}

extension ServiceHubKindX on ServiceHubKind {
  /// Backend kategoriya kaliti (ko'pchilik enum nomi bilan bir xil, 4 tasi farq qiladi).
  String get key => switch (this) {
    ServiceHubKind.gameZona => 'game_zona',
    ServiceHubKind.sportMaydon => 'sport_maydon',
    ServiceHubKind.kompUsta => 'kompyuter_usta',
    ServiceHubKind.boshqa => 'boshqa_xizmatlar',
    _ => name,
  };

  String get title => switch (this) {
    ServiceHubKind.sartarosh => 'Sartarosh',
    ServiceHubKind.salon => 'Salon',
    ServiceHubKind.futbol => 'Futbol',
    ServiceHubKind.ishchi => 'Ishchi',
    ServiceHubKind.usta => 'Usta',
    ServiceHubKind.elektrik => 'Elektrik',
    ServiceHubKind.santexnik => 'Santexnik',
    ServiceHubKind.tozalash => 'Tozalash',
    ServiceHubKind.avtoYordam => 'Avto-yordam',
    ServiceHubKind.konditsioner => 'Konditsioner',
    ServiceHubKind.enaga => 'Enaga',
    ServiceHubKind.repetitor => 'Repetitor',
    ServiceHubKind.dezinfeksiya => 'Dezinfeksiya',
    ServiceHubKind.texnikaUstasi => 'Texnika ustasi',
    ServiceHubKind.kuryerlik => 'Kuryerlik',
    ServiceHubKind.massajHijoma => 'Massaj va Hijoma',
    ServiceHubKind.hamshira => 'Hamshira',
    ServiceHubKind.stomatologiya => 'Stomatologiya',
    ServiceHubKind.tadbirlar => 'Tadbirlar',
    ServiceHubKind.bozorchi => 'Bozorchi',
    ServiceHubKind.oshxona => 'Oshxona',
    ServiceHubKind.gameZona => 'Game Zona',
    ServiceHubKind.sportMaydon => 'Sport maydonlari',
    ServiceHubKind.kompUsta => 'Komp Usta',
    ServiceHubKind.boshqa => 'Boshqa Xizmatlar',
    ServiceHubKind.yana => 'Yana xizmatlar',
  };

  String get hubSubtitle => switch (this) {
    ServiceHubKind.sartarosh => 'Yaqin atrofdagi sartaroshlar va band qilish',
    ServiceHubKind.salon => 'Salonda vaqt bron qilish',
    ServiceHubKind.futbol => 'Futbol maydonini band qilish',
    ServiceHubKind.ishchi => 'Ishchi yollash va kunlik ishlar',
    ServiceHubKind.usta => 'Usta chaqirish va tamlash',
    ServiceHubKind.elektrik => 'Elektr montaj va favqulodda chaqiruv',
    ServiceHubKind.santexnik => 'Santexnik va suv oqimi',
    ServiceHubKind.tozalash => 'Uy yoki ofis tozalash xizmati',
    ServiceHubKind.avtoYordam => 'Evakuator, akkumulyator, yol yordami',
    ServiceHubKind.konditsioner => 'Konditsioner montaj va profilaktika',
    ServiceHubKind.enaga => 'Bola qarovchi va enaga',
    ServiceHubKind.repetitor => 'Repetitor va oqituvchi xizmati',
    ServiceHubKind.dezinfeksiya => 'Uy, ofis va mashina dezinfeksiyasi',
    ServiceHubKind.texnikaUstasi => 'Kir yuvish, muzlatgich, TV tamlash',
    ServiceHubKind.kuryerlik => 'Hujjat va sovgalarni tezkor yetkazish',
    ServiceHubKind.massajHijoma => 'Massaj va Hijoma xizmatlari',
    ServiceHubKind.hamshira => 'Uyga hamshira chaqirish',
    ServiceHubKind.stomatologiya => 'Tish davolash — klinikada vaqt bron',
    ServiceHubKind.tadbirlar => 'Guruhlar — sahna, ovoz, qishloq va to\'y',
    ServiceHubKind.bozorchi => 'Ro\'zg\'or xaridlari va yetkazib berish',
    ServiceHubKind.oshxona => 'Restoranlar, kafelar va ovqatlanish joylari.',
    ServiceHubKind.gameZona => 'PS5, PC, VR klublari va o\'yin xonalari.',
    ServiceHubKind.sportMaydon => 'Futbol, tennis va boshqa sport maydonlari.',
    ServiceHubKind.kompUsta => 'Kompyuter va IT xizmatlari.',
    ServiceHubKind.boshqa => 'Aralash va boshqa turdagi xizmatlar.',
    ServiceHubKind.yana => 'Tez kunda qo\'shimcha xizmatlar qo\'shiladi...',
  };

  IconData get icon => switch (this) {
    ServiceHubKind.sartarosh => LucideIcons.scissors,
    ServiceHubKind.salon => LucideIcons.sparkles,
    ServiceHubKind.futbol => LucideIcons.trophy,
    ServiceHubKind.ishchi => LucideIcons.users,
    ServiceHubKind.usta => LucideIcons.wrench,
    ServiceHubKind.elektrik => LucideIcons.zap,
    ServiceHubKind.santexnik => LucideIcons.droplets,
    ServiceHubKind.tozalash => LucideIcons.sprayCan,
    ServiceHubKind.avtoYordam => LucideIcons.car,
    ServiceHubKind.konditsioner => LucideIcons.wind,
    ServiceHubKind.enaga => LucideIcons.baby,
    ServiceHubKind.repetitor => LucideIcons.bookOpen,
    ServiceHubKind.dezinfeksiya => LucideIcons.shieldCheck,
    ServiceHubKind.texnikaUstasi => LucideIcons.monitor,
    ServiceHubKind.kuryerlik => LucideIcons.bike,
    ServiceHubKind.massajHijoma => LucideIcons.hand,
    ServiceHubKind.hamshira => LucideIcons.heartPulse,
    ServiceHubKind.stomatologiya => LucideIcons.smile,
    ServiceHubKind.tadbirlar => LucideIcons.partyPopper,
    ServiceHubKind.bozorchi => LucideIcons.shoppingCart,
    ServiceHubKind.oshxona => LucideIcons.utensils,
    ServiceHubKind.gameZona => LucideIcons.gamepad2,
    ServiceHubKind.sportMaydon => Icons.sports_soccer,
    ServiceHubKind.kompUsta => LucideIcons.monitor,
    ServiceHubKind.boshqa => LucideIcons.layoutGrid,
    ServiceHubKind.yana => LucideIcons.moreHorizontal,
  };

  /// 3D icon rasm yo'li (3dicons.co). Bo'lmasa null → yuqoridagi [icon] ishlatiladi.
  String? get asset3d => switch (this) {
    ServiceHubKind.sartarosh => 'assets/images/services3d/sartarosh.png',
    ServiceHubKind.salon => 'assets/images/services3d/salon.png',
    ServiceHubKind.futbol => 'assets/images/services3d/futbol.png',
    ServiceHubKind.ishchi => 'assets/images/services3d/ishchi.png',
    ServiceHubKind.usta => 'assets/images/services3d/usta.png',
    ServiceHubKind.elektrik => 'assets/images/services3d/elektrik.png',
    ServiceHubKind.santexnik => 'assets/images/services3d/santexnik.png',
    ServiceHubKind.tozalash => 'assets/images/services3d/tozalash.png',
    ServiceHubKind.avtoYordam => 'assets/images/services3d/avtoYordam.png',
    ServiceHubKind.enaga => 'assets/images/services3d/enaga.png',
    ServiceHubKind.repetitor => 'assets/images/services3d/repetitor.png',
    ServiceHubKind.dezinfeksiya => 'assets/images/services3d/dezinfeksiya.png',
    ServiceHubKind.texnikaUstasi => 'assets/images/services3d/texnikaUstasi.png',
    ServiceHubKind.kuryerlik => 'assets/images/services3d/kuryerlik.png',
    ServiceHubKind.massajHijoma => 'assets/images/services3d/massajHijoma.png',
    ServiceHubKind.hamshira => 'assets/images/services3d/hamshira.png',
    ServiceHubKind.tadbirlar => 'assets/images/services3d/tadbirlar.png',
    ServiceHubKind.bozorchi => 'assets/images/services3d/bozorchi.png',
    ServiceHubKind.oshxona => 'assets/images/services3d/oshxona.png',
    ServiceHubKind.gameZona => 'assets/images/services3d/gameZona.png',
    ServiceHubKind.sportMaydon => 'assets/images/services3d/sportMaydon.png',
    ServiceHubKind.kompUsta => 'assets/images/services3d/kompUsta.png',
    ServiceHubKind.boshqa => 'assets/images/services3d/boshqa.png',
    ServiceHubKind.yana => 'assets/images/services3d/yana.png',
    // Aynan mos 3D icon yo'q — eng yaqin variant (lab/umbrella)
    ServiceHubKind.stomatologiya => 'assets/images/services3d/stomatologiya.png',
    ServiceHubKind.konditsioner => 'assets/images/services3d/konditsioner.png',
  };

  Color get accent => switch (this) {
    ServiceHubKind.sartarosh => Colors.blue,
    ServiceHubKind.salon => Colors.pink,
    ServiceHubKind.futbol => Colors.green,
    ServiceHubKind.ishchi => Colors.orange,
    ServiceHubKind.usta => Colors.teal,
    ServiceHubKind.elektrik => const Color(0xFFD97706),
    ServiceHubKind.santexnik => Colors.lightBlue,
    ServiceHubKind.tozalash => Colors.cyan,
    ServiceHubKind.avtoYordam => Colors.deepOrange,
    ServiceHubKind.konditsioner => Colors.indigo,
    ServiceHubKind.enaga => Colors.purple,
    ServiceHubKind.repetitor => Colors.deepPurple,
    ServiceHubKind.dezinfeksiya => const Color(0xFF10B981),
    ServiceHubKind.texnikaUstasi => Colors.blueGrey,
    ServiceHubKind.kuryerlik => Colors.amber,
    ServiceHubKind.massajHijoma => const Color(0xFF795548),
    ServiceHubKind.hamshira => const Color(0xFFEF4444),
    ServiceHubKind.stomatologiya => const Color(0xFF0EA5E9),
    ServiceHubKind.tadbirlar => const Color(0xFFE91E63),
    ServiceHubKind.bozorchi => const Color(0xFFFF9800),
    ServiceHubKind.oshxona => const Color(0xFFF44336),
    ServiceHubKind.gameZona => const Color(0xFF673AB7),
    ServiceHubKind.sportMaydon => const Color(0xFF4CAF50),
    ServiceHubKind.kompUsta => const Color(0xFF607D8B),
    ServiceHubKind.boshqa => const Color(0xFF9E9E9E),
    ServiceHubKind.yana => const Color(0xFF9E9E9E),
  };

  List<({String label, double basePrice})> get variants => switch (this) {
    ServiceHubKind.sartarosh => const [
      (label: 'Erkaklar kesimi', basePrice: 50000),
      (label: 'Soqol olish', basePrice: 25000),
      (label: 'Bolalar kesimi', basePrice: 35000),
      (label: 'Styling', basePrice: 60000),
    ],
    ServiceHubKind.salon => const [
      (label: 'Manikyur', basePrice: 70000),
      (label: 'Pedikyur', basePrice: 90000),
      (label: 'Soch turmagi', basePrice: 80000),
      (label: 'Make-up', basePrice: 150000),
    ],
    ServiceHubKind.futbol => const [
      (label: '1 soat (kichik maydon)', basePrice: 200000),
      (label: '1 soat (katta maydon)', basePrice: 350000),
      (label: '2 soat (kichik maydon)', basePrice: 380000),
      (label: '2 soat (katta maydon)', basePrice: 650000),
    ],
    ServiceHubKind.ishchi => const [
      (label: 'Yuk kotoruvchi (1 kishi)', basePrice: 150000),
      (label: 'Yuk kotoruvchi (2 kishi)', basePrice: 280000),
      (label: 'Qora ish - 4 soat', basePrice: 200000),
      (label: 'Qora ish - kunlik', basePrice: 400000),
    ],
    ServiceHubKind.usta => const [
      (label: 'Mebel yigish', basePrice: 150000),
      (label: 'Eshik/oyna tamiri', basePrice: 120000),
      (label: 'Devorga osish/biriktirish', basePrice: 80000),
      (label: 'Boshqa tamlash', basePrice: 100000),
    ],
    ServiceHubKind.elektrik => const [
      (label: 'Rozetka/lyustra montaj', basePrice: 100000),
      (label: 'Simlash', basePrice: 250000),
      (label: 'Shoshilinch chaqiruv', basePrice: 200000),
      (label: 'Uy elektr tekshiruvi', basePrice: 180000),
    ],
    ServiceHubKind.santexnik => const [
      (label: 'Smesitel almashtirish', basePrice: 120000),
      (label: 'Toshma/probka tozalash', basePrice: 150000),
      (label: 'Quvur ulash', basePrice: 200000),
      (label: 'Shoshilinch chaqiruv', basePrice: 250000),
    ],
    ServiceHubKind.tozalash => const [
      (label: '1 xonali kvartira', basePrice: 200000),
      (label: '2 xonali kvartira', basePrice: 320000),
      (label: '3 xonali kvartira', basePrice: 450000),
      (label: 'Ofis (50 m²)', basePrice: 400000),
    ],
    ServiceHubKind.avtoYordam => const [
      (label: 'Evakuator', basePrice: 250000),
      (label: 'Akkumulyator quvvatlash', basePrice: 80000),
      (label: 'Shinopola (1 gildirak)', basePrice: 70000),
      (label: 'Yol ustasi', basePrice: 150000),
    ],
    ServiceHubKind.konditsioner => const [
      (label: 'Montaj', basePrice: 600000),
      (label: 'Demontaj', basePrice: 250000),
      (label: 'Profilaktika tozalash', basePrice: 180000),
      (label: 'Gaz toldirish', basePrice: 350000),
    ],
    ServiceHubKind.enaga => const [
      (label: 'Soatlik (3 soat)', basePrice: 120000),
      (label: 'Yarim kun (5 soat)', basePrice: 200000),
      (label: 'Toliq kun (10 soat)', basePrice: 380000),
      (label: 'Tunda (8 soat)', basePrice: 350000),
    ],
    ServiceHubKind.repetitor => const [
      (label: 'Matematika (1 dars)', basePrice: 120000),
      (label: 'Ingliz tili (1 dars)', basePrice: 100000),
      (label: 'Fizika (1 dars)', basePrice: 130000),
      (label: 'Test tayyorlov (1 dars)', basePrice: 150000),
    ],
    ServiceHubKind.dezinfeksiya => const [
      (label: 'Kvartira dezinfeksiyasi', basePrice: 150000),
      (label: 'Ofis dezinfeksiyasi', basePrice: 250000),
      (label: 'Mashina dezinfeksiyasi', basePrice: 100000),
      (label: 'Maktab/bogcha', basePrice: 400000),
    ],
    ServiceHubKind.texnikaUstasi => const [
      (label: 'Kir yuvish mashinasi', basePrice: 150000),
      (label: 'Muzlatgich tamlash', basePrice: 180000),
      (label: 'Televizor tamlash', basePrice: 120000),
      (label: 'Mikroto`lqinli pech', basePrice: 80000),
    ],
    ServiceHubKind.kuryerlik => const [
      (label: 'Hujjat yetkazish', basePrice: 30000),
      (label: 'Sovga yetkazish', basePrice: 50000),
      (label: 'Kichik yuk (5 kg)', basePrice: 40000),
      (label: 'Katta yuk (20 kg)', basePrice: 80000),
    ],
    ServiceHubKind.massajHijoma => const [
      (label: 'Massaj (60 daqiqa)', basePrice: 150000),
      (label: 'Hijoma (erkaklar)', basePrice: 200000),
      (label: 'Hijoma (ayollar)', basePrice: 200000),
      (label: 'Spa paket', basePrice: 350000),
    ],
    ServiceHubKind.hamshira => const [
      (label: 'Uyga hamshira (3 soat)', basePrice: 100000),
      (label: 'In`ektsiya', basePrice: 30000),
      (label: 'Qon tahlili (uyda)', basePrice: 120000),
      (label: 'Tun bo`yi hamshira', basePrice: 300000),
    ],
    ServiceHubKind.stomatologiya => const [
      (label: 'Ko\'rik va maslahat', basePrice: 80000),
      (label: 'Professional tozalash', basePrice: 150000),
      (label: 'Plomba', basePrice: 200000),
      (label: 'Oqartirish', basePrice: 350000),
    ],
    ServiceHubKind.tadbirlar => const [
      (label: 'Toy rejissyor', basePrice: 2000000),
      (label: 'Tug`ilgan kun', basePrice: 500000),
      (label: 'Dam olish joyi bron', basePrice: 300000),
      (label: 'Korporativ tadbir', basePrice: 1500000),
    ],
    ServiceHubKind.bozorchi => const [
      (label: 'Oziq-ovqat xaridi', basePrice: 50000),
      (label: 'Katta bozorlik', basePrice: 100000),
      (label: 'Dori-darmon xaridi', basePrice: 40000),
    ],
    ServiceHubKind.oshxona => const [
      (label: 'Stol bron qilish (2 kishilik)', basePrice: 50000),
      (label: 'Stol bron qilish (4+ kishilik)', basePrice: 100000),
      (label: 'VIP xona', basePrice: 200000),
    ],
    ServiceHubKind.gameZona => const [
      (label: 'PS5 xonasi (1 soat)', basePrice: 30000),
      (label: 'PC hududi (1 soat)', basePrice: 20000),
      (label: 'VR o\'yinlar (30 min)', basePrice: 40000),
    ],
    ServiceHubKind.sportMaydon => const [
      (label: 'Tennis korti (1 soat)', basePrice: 100000),
      (label: 'Basketbol maydoni', basePrice: 80000),
      (label: 'Voleybol maydoni', basePrice: 80000),
    ],
    ServiceHubKind.kompUsta => const [
      (label: 'Windows o\'rnatish', basePrice: 70000),
      (label: 'Format qilish', basePrice: 50000),
      (label: 'PC terish', basePrice: 150000),
    ],
    ServiceHubKind.boshqa => const [(label: 'Xizmat haqi', basePrice: 100000)],
    ServiceHubKind.yana => const [(label: 'Boshqa xizmat', basePrice: 100000)],
  };
}
