import 'package:flutter/material.dart';
import 'package:lucide_icons_flutter/lucide_icons.dart';

/// Asosiy ekrandagi katakchalar va yangi qo'shimcha xizmatlar bilan mos
/// keladigan barcha xizmat turlari.
enum ServiceHubKind {
  sartarosh,
  salon,
  futbol,
  ishchi,
  usta,
  elektrik,
  santexnik,
  tozalash,
  avtoYordam,
  konditsioner,
  enaga,
  repetitor,
  // 6 ta YANGI:
  dezinfeksiya,
  texnikaUstasi,
  kuryerlik,
  massajHijoma,
  hamshira,
  stomatologiya,
  tadbirlar,
  yana,
}

extension ServiceHubKindX on ServiceHubKind {
  String get title => switch (this) {
        ServiceHubKind.sartarosh => 'Sartarosh',
        ServiceHubKind.salon => 'Salon',
        ServiceHubKind.futbol => 'Futbol',
        ServiceHubKind.ishchi => 'Ishchi',
        ServiceHubKind.usta => 'Usta',
        ServiceHubKind.elektrik => 'Elektrik',
        ServiceHubKind.santexnik => 'Santexnik',
        ServiceHubKind.tozalash => 'Tozalash',
        ServiceHubKind.avtoYordam => 'Avto-yordam',
        ServiceHubKind.konditsioner => 'Konditsioner',
        ServiceHubKind.enaga => 'Enaga',
        ServiceHubKind.repetitor => 'Repetitor',
        ServiceHubKind.dezinfeksiya => 'Dezinfeksiya',
        ServiceHubKind.texnikaUstasi => 'Texnika ustasi',
        ServiceHubKind.kuryerlik => 'Kuryerlik',
        ServiceHubKind.massajHijoma => 'Massaj va Hijoma',
        ServiceHubKind.hamshira => 'Hamshira',
        ServiceHubKind.stomatologiya => 'Stomatologiya',
        ServiceHubKind.tadbirlar => 'Tadbirlar',
        ServiceHubKind.yana => 'Yana xizmatlar',
      };

  String get hubSubtitle => switch (this) {
        ServiceHubKind.sartarosh => 'Yaqin atrofdagi sartaroshlar va band qilish',
        ServiceHubKind.salon => 'Salonda vaqt bron qilish',
        ServiceHubKind.futbol => 'Futbol maydonini band qilish',
        ServiceHubKind.ishchi => 'Ishchi yollash va kunlik ishlar',
        ServiceHubKind.usta => 'Usta chaqirish va tamlash',
        ServiceHubKind.elektrik => 'Elektr montaj va favqulodda chaqiruv',
        ServiceHubKind.santexnik => 'Santexnik va suv oqimi',
        ServiceHubKind.tozalash => 'Uy yoki ofis tozalash xizmati',
        ServiceHubKind.avtoYordam => 'Evakuator, akkumulyator, yol yordami',
        ServiceHubKind.konditsioner => 'Konditsioner montaj va profilaktika',
        ServiceHubKind.enaga => 'Bola qarovchi va enaga',
        ServiceHubKind.repetitor => 'Repetitor va oqituvchi xizmati',
        ServiceHubKind.dezinfeksiya => 'Uy, ofis va mashina dezinfeksiyasi',
        ServiceHubKind.texnikaUstasi => 'Kir yuvish, muzlatgich, TV tamlash',
        ServiceHubKind.kuryerlik => 'Hujjat va sovgalarni tezkor yetkazish',
        ServiceHubKind.massajHijoma => 'Massaj va Hijoma xizmatlari',
        ServiceHubKind.hamshira => 'Uyga hamshira chaqirish',
        ServiceHubKind.stomatologiya => 'Tish davolash — klinikada vaqt bron',
        ServiceHubKind.tadbirlar => 'Guruhlar — sahna, ovoz, qishloq va to\'y',
        ServiceHubKind.yana => 'Boshqa xizmatlar va yordam',
      };

  IconData get icon => switch (this) {
        ServiceHubKind.sartarosh => LucideIcons.scissors,
        ServiceHubKind.salon => LucideIcons.sparkles,
        ServiceHubKind.futbol => LucideIcons.trophy,
        ServiceHubKind.ishchi => LucideIcons.users,
        ServiceHubKind.usta => LucideIcons.wrench,
        ServiceHubKind.elektrik => LucideIcons.zap,
        ServiceHubKind.santexnik => LucideIcons.droplets,
        ServiceHubKind.tozalash => LucideIcons.sprayCan,
        ServiceHubKind.avtoYordam => LucideIcons.car,
        ServiceHubKind.konditsioner => LucideIcons.wind,
        ServiceHubKind.enaga => LucideIcons.baby,
        ServiceHubKind.repetitor => LucideIcons.bookOpen,
        ServiceHubKind.dezinfeksiya => LucideIcons.shieldCheck,
        ServiceHubKind.texnikaUstasi => LucideIcons.monitor,
        ServiceHubKind.kuryerlik => LucideIcons.bike,
        ServiceHubKind.massajHijoma => LucideIcons.hand,
        ServiceHubKind.hamshira => LucideIcons.heartPulse,
        ServiceHubKind.stomatologiya => LucideIcons.smile,
        ServiceHubKind.tadbirlar => LucideIcons.partyPopper,
        ServiceHubKind.yana => LucideIcons.moreHorizontal,
      };

  Color get accent => switch (this) {
        ServiceHubKind.sartarosh => Colors.blue,
        ServiceHubKind.salon => Colors.pink,
        ServiceHubKind.futbol => Colors.green,
        ServiceHubKind.ishchi => Colors.orange,
        ServiceHubKind.usta => Colors.teal,
        ServiceHubKind.elektrik => const Color(0xFFD97706),
        ServiceHubKind.santexnik => Colors.lightBlue,
        ServiceHubKind.tozalash => Colors.cyan,
        ServiceHubKind.avtoYordam => Colors.deepOrange,
        ServiceHubKind.konditsioner => Colors.indigo,
        ServiceHubKind.enaga => Colors.purple,
        ServiceHubKind.repetitor => Colors.deepPurple,
        ServiceHubKind.dezinfeksiya => const Color(0xFF10B981),
        ServiceHubKind.texnikaUstasi => Colors.blueGrey,
        ServiceHubKind.kuryerlik => Colors.amber,
        ServiceHubKind.massajHijoma => const Color(0xFF795548),
        ServiceHubKind.hamshira => const Color(0xFFEF4444),
        ServiceHubKind.stomatologiya => const Color(0xFF0EA5E9),
        ServiceHubKind.tadbirlar => const Color(0xFFE91E63),
        ServiceHubKind.yana => Colors.blueGrey,
      };

  List<({String label, double basePrice})> get variants => switch (this) {
        ServiceHubKind.sartarosh => const [
            (label: 'Erkaklar kesimi', basePrice: 50000),
            (label: 'Soqol olish', basePrice: 25000),
            (label: 'Bolalar kesimi', basePrice: 35000),
            (label: 'Styling', basePrice: 60000),
          ],
        ServiceHubKind.salon => const [
            (label: 'Manikyur', basePrice: 70000),
            (label: 'Pedikyur', basePrice: 90000),
            (label: 'Soch turmagi', basePrice: 80000),
            (label: 'Make-up', basePrice: 150000),
          ],
        ServiceHubKind.futbol => const [
            (label: '1 soat (kichik maydon)', basePrice: 200000),
            (label: '1 soat (katta maydon)', basePrice: 350000),
            (label: '2 soat (kichik maydon)', basePrice: 380000),
            (label: '2 soat (katta maydon)', basePrice: 650000),
          ],
        ServiceHubKind.ishchi => const [
            (label: 'Yuk kotoruvchi (1 kishi)', basePrice: 150000),
            (label: 'Yuk kotoruvchi (2 kishi)', basePrice: 280000),
            (label: 'Qora ish - 4 soat', basePrice: 200000),
            (label: 'Qora ish - kunlik', basePrice: 400000),
          ],
        ServiceHubKind.usta => const [
            (label: 'Mebel yigish', basePrice: 150000),
            (label: 'Eshik/oyna tamiri', basePrice: 120000),
            (label: 'Devorga osish/biriktirish', basePrice: 80000),
            (label: 'Boshqa tamlash', basePrice: 100000),
          ],
        ServiceHubKind.elektrik => const [
            (label: 'Rozetka/lyustra montaj', basePrice: 100000),
            (label: 'Simlash', basePrice: 250000),
            (label: 'Shoshilinch chaqiruv', basePrice: 200000),
            (label: 'Uy elektr tekshiruvi', basePrice: 180000),
          ],
        ServiceHubKind.santexnik => const [
            (label: 'Smesitel almashtirish', basePrice: 120000),
            (label: 'Toshma/probka tozalash', basePrice: 150000),
            (label: 'Quvur ulash', basePrice: 200000),
            (label: 'Shoshilinch chaqiruv', basePrice: 250000),
          ],
        ServiceHubKind.tozalash => const [
            (label: '1 xonali kvartira', basePrice: 200000),
            (label: '2 xonali kvartira', basePrice: 320000),
            (label: '3 xonali kvartira', basePrice: 450000),
            (label: 'Ofis (50 m²)', basePrice: 400000),
          ],
        ServiceHubKind.avtoYordam => const [
            (label: 'Evakuator', basePrice: 250000),
            (label: 'Akkumulyator quvvatlash', basePrice: 80000),
            (label: 'Shinopola (1 gildirak)', basePrice: 70000),
            (label: 'Yol ustasi', basePrice: 150000),
          ],
        ServiceHubKind.konditsioner => const [
            (label: 'Montaj', basePrice: 600000),
            (label: 'Demontaj', basePrice: 250000),
            (label: 'Profilaktika tozalash', basePrice: 180000),
            (label: 'Gaz toldirish', basePrice: 350000),
          ],
        ServiceHubKind.enaga => const [
            (label: 'Soatlik (3 soat)', basePrice: 120000),
            (label: 'Yarim kun (5 soat)', basePrice: 200000),
            (label: 'Toliq kun (10 soat)', basePrice: 380000),
            (label: 'Tunda (8 soat)', basePrice: 350000),
          ],
        ServiceHubKind.repetitor => const [
            (label: 'Matematika (1 dars)', basePrice: 120000),
            (label: 'Ingliz tili (1 dars)', basePrice: 100000),
            (label: 'Fizika (1 dars)', basePrice: 130000),
            (label: 'Test tayyorlov (1 dars)', basePrice: 150000),
          ],
        ServiceHubKind.dezinfeksiya => const [
            (label: 'Kvartira dezinfeksiyasi', basePrice: 150000),
            (label: 'Ofis dezinfeksiyasi', basePrice: 250000),
            (label: 'Mashina dezinfeksiyasi', basePrice: 100000),
            (label: 'Maktab/bogcha', basePrice: 400000),
          ],
        ServiceHubKind.texnikaUstasi => const [
            (label: 'Kir yuvish mashinasi', basePrice: 150000),
            (label: 'Muzlatgich tamlash', basePrice: 180000),
            (label: 'Televizor tamlash', basePrice: 120000),
            (label: 'Mikroto`lqinli pech', basePrice: 80000),
          ],
        ServiceHubKind.kuryerlik => const [
            (label: 'Hujjat yetkazish', basePrice: 30000),
            (label: 'Sovga yetkazish', basePrice: 50000),
            (label: 'Kichik yuk (5 kg)', basePrice: 40000),
            (label: 'Katta yuk (20 kg)', basePrice: 80000),
          ],
        ServiceHubKind.massajHijoma => const [
            (label: 'Massaj (60 daqiqa)', basePrice: 150000),
            (label: 'Hijoma (erkaklar)', basePrice: 200000),
            (label: 'Hijoma (ayollar)', basePrice: 200000),
            (label: 'Spa paket', basePrice: 350000),
          ],
        ServiceHubKind.hamshira => const [
            (label: 'Uyga hamshira (3 soat)', basePrice: 100000),
            (label: 'In`ektsiya', basePrice: 30000),
            (label: 'Qon tahlili (uyda)', basePrice: 120000),
            (label: 'Tun bo`yi hamshira', basePrice: 300000),
          ],
        ServiceHubKind.stomatologiya => const [
            (label: 'Ko\'rik va maslahat', basePrice: 80000),
            (label: 'Professional tozalash', basePrice: 150000),
            (label: 'Plomba', basePrice: 200000),
            (label: 'Oqartirish', basePrice: 350000),
          ],
        ServiceHubKind.tadbirlar => const [
            (label: 'Toy rejissyor', basePrice: 2000000),
            (label: 'Tug`ilgan kun', basePrice: 500000),
            (label: 'Dam olish joyi bron', basePrice: 300000),
            (label: 'Korporativ tadbir', basePrice: 1500000),
          ],
        ServiceHubKind.yana => const [
            (label: 'Boshqa xizmat', basePrice: 100000),
          ],
      };
}
