"""add complaints table

Revision ID: 0903e7db0e81
Revises: dc44c41514df
Create Date: 2026-09-06 13:27:01.093381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by alembic.
revision: str = '0903e7db0e81'
down_revision: Union[str, None] = 'dc44c41514df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('complaints',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('reporter_user_id', sa.Integer(), nullable=False),
    sa.Column('target_provider_id', sa.Integer(), nullable=True),
    sa.Column('target_user_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('ai_summary', sa.String(length=500), nullable=True),
    sa.Column('has_interaction', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('admin_note', sa.Text(), nullable=True),
    sa.Column('resolved_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reporter_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_provider_id'], ['providers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_complaints_created_at'), 'complaints', ['created_at'], unique=False)
    op.create_index(op.f('ix_complaints_kind'), 'complaints', ['kind'], unique=False)
    op.create_index('ix_complaints_provider_status', 'complaints', ['target_provider_id', 'status'], unique=False)
    op.create_index(op.f('ix_complaints_reporter_user_id'), 'complaints', ['reporter_user_id'], unique=False)
    op.create_index(op.f('ix_complaints_status'), 'complaints', ['status'], unique=False)
    op.create_index('ix_complaints_status_created', 'complaints', ['status', 'created_at'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_complaints_status_created', table_name='complaints')
    op.drop_index(op.f('ix_complaints_status'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_reporter_user_id'), table_name='complaints')
    op.drop_index('ix_complaints_provider_status', table_name='complaints')
    op.drop_index(op.f('ix_complaints_kind'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_created_at'), table_name='complaints')
    op.drop_table('complaints')
    # ### end Alembic commands ###
