"""sync models with migrations: add 37 missing tables

Revision ID: 6b2478ceb5c8
Revises: 2bbc0e954e83
Create Date: 2026-09-06 06:50:51.604837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by alembic.
revision: str = '6b2478ceb5c8'
down_revision: Union[str, None] = '2bbc0e954e83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_roles_name'), 'admin_roles', ['name'], unique=True)
    op.create_table('exercises',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.String(length=20), nullable=False),
    sa.Column('media_id', sa.String(length=64), nullable=True),
    sa.Column('gif_url', sa.String(length=500), nullable=True),
    sa.Column('name_en', sa.String(length=255), nullable=False),
    sa.Column('name_uz', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('body_part', sa.String(length=50), nullable=True),
    sa.Column('equipment', sa.String(length=50), nullable=True),
    sa.Column('target', sa.String(length=100), nullable=True),
    sa.Column('muscle_group', sa.String(length=100), nullable=True),
    sa.Column('secondary_muscles', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('instructions_en', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('instructions_uz', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercises_body_part'), 'exercises', ['body_part'], unique=False)
    op.create_index(op.f('ix_exercises_category'), 'exercises', ['category'], unique=False)
    op.create_index(op.f('ix_exercises_equipment'), 'exercises', ['equipment'], unique=False)
    op.create_index(op.f('ix_exercises_external_id'), 'exercises', ['external_id'], unique=True)
    op.create_index(op.f('ix_exercises_name_uz'), 'exercises', ['name_uz'], unique=False)
    op.create_index(op.f('ix_exercises_target'), 'exercises', ['target'], unique=False)
    op.create_table('finance_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('invite_code', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finance_groups_invite_code'), 'finance_groups', ['invite_code'], unique=True)
    op.create_index(op.f('ix_finance_groups_owner_id'), 'finance_groups', ['owner_id'], unique=False)
    op.create_table('product_catalog',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('average_price', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_catalog_name'), 'product_catalog', ['name'], unique=False)
    op.create_table('promos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('subtitle', sa.String(length=500), nullable=False),
    sa.Column('badge', sa.String(length=50), nullable=False),
    sa.Column('colors', sa.String(length=255), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alarms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('hour', sa.Integer(), nullable=False),
    sa.Column('minute', sa.Integer(), nullable=False),
    sa.Column('repeat_days', sa.String(length=20), nullable=False),
    sa.Column('ringtone', sa.String(length=50), nullable=False),
    sa.Column('mission_type', sa.String(length=20), nullable=False),
    sa.Column('mission_config', sa.JSON(), nullable=False),
    sa.Column('snooze_enabled', sa.Boolean(), nullable=False),
    sa.Column('snooze_minutes', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alarms_user_id'), 'alarms', ['user_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('admin_user_id', sa.Integer(), nullable=True),
    sa.Column('admin_name', sa.String(length=150), nullable=True),
    sa.Column('section', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('path', sa.String(length=300), nullable=False),
    sa.Column('detail', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['admin_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_admin_user_id'), 'audit_logs', ['admin_user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_section'), 'audit_logs', ['section'], unique=False)
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('prize', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('require_completed_order', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_category_id'), 'campaigns', ['category_id'], unique=False)
    op.create_index(op.f('ix_campaigns_ends_at'), 'campaigns', ['ends_at'], unique=False)
    op.create_index(op.f('ix_campaigns_is_active'), 'campaigns', ['is_active'], unique=False)
    op.create_index(op.f('ix_campaigns_starts_at'), 'campaigns', ['starts_at'], unique=False)
    op.create_table('daily_activity',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('steps', sa.Integer(), nullable=False),
    sa.Column('calories', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_daily_activity_user_date')
    )
    op.create_index(op.f('ix_daily_activity_date'), 'daily_activity', ['date'], unique=False)
    op.create_index(op.f('ix_daily_activity_user_id'), 'daily_activity', ['user_id'], unique=False)
    op.create_table('device_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=512), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_tokens_id'), 'device_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_device_tokens_token'), 'device_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_device_tokens_user_id'), 'device_tokens', ['user_id'], unique=False)
    op.create_index('ix_device_tokens_user_id_token', 'device_tokens', ['user_id', 'token'], unique=False)
    op.create_table('finance_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finance_records_user_id'), 'finance_records', ['user_id'], unique=False)
    op.create_table('listings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category_key', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('is_negotiable', sa.Boolean(), nullable=False),
    sa.Column('condition', sa.Enum('new', 'like_new', 'good', 'used', 'parts', name='listingcondition', native_enum=False, length=20), nullable=False),
    sa.Column('attributes', sa.JSON(), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('active', 'sold', 'expired', 'hidden', name='listingstatus', native_enum=False, length=20), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sold_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_listings_category_key'), 'listings', ['category_key'], unique=False)
    op.create_index(op.f('ix_listings_expires_at'), 'listings', ['expires_at'], unique=False)
    op.create_index(op.f('ix_listings_status'), 'listings', ['status'], unique=False)
    op.create_index(op.f('ix_listings_user_id'), 'listings', ['user_id'], unique=False)
    op.create_table('meal_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('meal_type', sa.String(length=20), nullable=False),
    sa.Column('dish_name', sa.String(length=255), nullable=False),
    sa.Column('portion_grams', sa.Float(), nullable=True),
    sa.Column('calories', sa.Float(), nullable=False),
    sa.Column('protein_g', sa.Float(), nullable=False),
    sa.Column('fat_g', sa.Float(), nullable=False),
    sa.Column('carbs_g', sa.Float(), nullable=False),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('ai_confidence', sa.Float(), nullable=True),
    sa.Column('logged_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meal_logs_logged_at'), 'meal_logs', ['logged_at'], unique=False)
    op.create_index(op.f('ix_meal_logs_user_id'), 'meal_logs', ['user_id'], unique=False)
    op.create_table('nutrition_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sex', sa.String(length=10), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('height_cm', sa.Float(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('activity_level', sa.String(length=20), nullable=False),
    sa.Column('goal', sa.String(length=20), nullable=False),
    sa.Column('manual_calorie_goal', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nutrition_profiles_user_id'), 'nutrition_profiles', ['user_id'], unique=True)
    op.create_table('planned_payments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_recurring', sa.Boolean(), nullable=False),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('is_notified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_planned_payments_user_id'), 'planned_payments', ['user_id'], unique=False)
    op.create_table('plans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('is_notified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plans_user_id'), 'plans', ['user_id'], unique=False)
    op.create_table('premium_payments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('method', sa.String(length=30), nullable=False),
    sa.Column('note', sa.String(length=300), nullable=True),
    sa.Column('confirmed_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_premium_payments_created_at'), 'premium_payments', ['created_at'], unique=False)
    op.create_index(op.f('ix_premium_payments_status'), 'premium_payments', ['status'], unique=False)
    op.create_index(op.f('ix_premium_payments_user_id'), 'premium_payments', ['user_id'], unique=False)
    op.create_table('product_price_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product_catalog.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_price_entries_product_id'), 'product_price_entries', ['product_id'], unique=False)
    op.create_table('shopping_lists',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('items', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('total_estimated_price', sa.Float(), nullable=False),
    sa.Column('total_actual_price', sa.Float(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('is_ordered', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shopping_lists_user_id'), 'shopping_lists', ['user_id'], unique=False)
    op.create_table('support_tickets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=True),
    sa.Column('last_message', sa.String(length=300), nullable=True),
    sa.Column('unread_admin', sa.Integer(), nullable=False),
    sa.Column('unread_user', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_support_tickets_created_at'), 'support_tickets', ['created_at'], unique=False)
    op.create_index(op.f('ix_support_tickets_last_message_at'), 'support_tickets', ['last_message_at'], unique=False)
    op.create_index(op.f('ix_support_tickets_status'), 'support_tickets', ['status'], unique=False)
    op.create_index(op.f('ix_support_tickets_user_id'), 'support_tickets', ['user_id'], unique=False)
    op.create_table('todos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_todos_user_id'), 'todos', ['user_id'], unique=False)
    op.create_table('workout_plans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('goal', sa.String(length=30), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('days_per_week', sa.Integer(), nullable=False),
    sa.Column('equipment_mode', sa.String(length=20), nullable=False),
    sa.Column('days', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('reminder_time', sa.String(length=5), nullable=True),
    sa.Column('reminder_weekdays', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workout_plans_user_id'), 'workout_plans', ['user_id'], unique=False)
    op.create_table('alarm_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('alarm_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mission_type', sa.String(length=20), nullable=False),
    sa.Column('fired_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('dismissed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dismiss_seconds', sa.Integer(), nullable=True),
    sa.Column('snooze_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['alarm_id'], ['alarms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alarm_logs_alarm_id'), 'alarm_logs', ['alarm_id'], unique=False)
    op.create_index(op.f('ix_alarm_logs_fired_at'), 'alarm_logs', ['fired_at'], unique=False)
    op.create_index(op.f('ix_alarm_logs_user_id'), 'alarm_logs', ['user_id'], unique=False)
    op.create_table('blocked_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blocked_users_provider_id'), 'blocked_users', ['provider_id'], unique=False)
    op.create_index(op.f('ix_blocked_users_user_id'), 'blocked_users', ['user_id'], unique=False)
    op.create_table('call_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('caller_id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['caller_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_call_history_caller_id'), 'call_history', ['caller_id'], unique=False)
    op.create_index(op.f('ix_call_history_provider_id'), 'call_history', ['provider_id'], unique=False)
    op.create_index(op.f('ix_call_history_receiver_id'), 'call_history', ['receiver_id'], unique=False)
    op.create_table('campaign_votes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'user_id', name='uq_campaign_vote_once')
    )
    op.create_index(op.f('ix_campaign_votes_campaign_id'), 'campaign_votes', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_campaign_votes_provider_id'), 'campaign_votes', ['provider_id'], unique=False)
    op.create_index(op.f('ix_campaign_votes_user_id'), 'campaign_votes', ['user_id'], unique=False)
    op.create_table('job_posts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('photos', sa.Text(), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('budget', sa.Float(), nullable=True),
    sa.Column('needed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('open', 'assigned', 'completed', 'cancelled', 'expired', name='jobstatus'), nullable=False),
    sa.Column('assigned_provider_id', sa.Integer(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_provider_id'], ['providers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_posts_assigned_provider_id'), 'job_posts', ['assigned_provider_id'], unique=False)
    op.create_index(op.f('ix_job_posts_category_id'), 'job_posts', ['category_id'], unique=False)
    op.create_index(op.f('ix_job_posts_created_at'), 'job_posts', ['created_at'], unique=False)
    op.create_index(op.f('ix_job_posts_expires_at'), 'job_posts', ['expires_at'], unique=False)
    op.create_index(op.f('ix_job_posts_status'), 'job_posts', ['status'], unique=False)
    op.create_index(op.f('ix_job_posts_user_id'), 'job_posts', ['user_id'], unique=False)
    op.create_table('listing_photos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_listing_photos_listing_id'), 'listing_photos', ['listing_id'], unique=False)
    op.create_table('provider_blocked_times',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provider_blocked_times_provider_id'), 'provider_blocked_times', ['provider_id'], unique=False)
    op.create_table('provider_fraud_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.Column('total_orders', sa.Integer(), nullable=False),
    sa.Column('no_show_count', sa.Integer(), nullable=False),
    sa.Column('disputed_count', sa.Integer(), nullable=False),
    sa.Column('flexible_skip_pattern', sa.Integer(), nullable=False),
    sa.Column('flag_level', sa.Enum('normal', 'warning', 'alert', 'suspended', name='fraudflaglevel'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provider_fraud_stats_month'), 'provider_fraud_stats', ['month'], unique=False)
    op.create_index(op.f('ix_provider_fraud_stats_provider_id'), 'provider_fraud_stats', ['provider_id'], unique=False)
    op.create_table('support_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('sender', sa.String(length=10), nullable=False),
    sa.Column('admin_name', sa.String(length=100), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['support_tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_support_messages_created_at'), 'support_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_support_messages_ticket_id'), 'support_messages', ['ticket_id'], unique=False)
    op.create_table('workout_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('day_index', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_exercises', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('duration_min', sa.Integer(), nullable=True),
    sa.Column('calories_burned', sa.Float(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['workout_plans.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workout_logs_date'), 'workout_logs', ['date'], unique=False)
    op.create_index(op.f('ix_workout_logs_user_id'), 'workout_logs', ['user_id'], unique=False)
    op.create_table('call_deals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('call_id', sa.String(length=64), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('provider_user_id', sa.Integer(), nullable=False),
    sa.Column('category_key', sa.String(length=80), nullable=True),
    sa.Column('provider_response', sa.String(length=16), nullable=True),
    sa.Column('client_response', sa.String(length=16), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['provider_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_call_deals_call_id'), 'call_deals', ['call_id'], unique=True)
    op.create_index(op.f('ix_call_deals_client_id'), 'call_deals', ['client_id'], unique=False)
    op.create_index(op.f('ix_call_deals_created_at'), 'call_deals', ['created_at'], unique=False)
    op.create_index(op.f('ix_call_deals_provider_user_id'), 'call_deals', ['provider_user_id'], unique=False)
    op.create_index(op.f('ix_call_deals_status'), 'call_deals', ['status'], unique=False)
    op.create_table('direct_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job_posts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_direct_messages_created_at'), 'direct_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_direct_messages_job_id'), 'direct_messages', ['job_id'], unique=False)
    op.create_index(op.f('ix_direct_messages_recipient_id'), 'direct_messages', ['recipient_id'], unique=False)
    op.create_index(op.f('ix_direct_messages_sender_id'), 'direct_messages', ['sender_id'], unique=False)
    op.create_index('ix_dm_pair', 'direct_messages', ['sender_id', 'recipient_id'], unique=False)
    op.create_index('ix_dm_recipient_unread', 'direct_messages', ['recipient_id', 'is_read'], unique=False)
    op.create_table('disputes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('refund_amount', sa.Float(), nullable=False),
    sa.Column('resolved_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_disputes_created_at'), 'disputes', ['created_at'], unique=False)
    op.create_index(op.f('ix_disputes_order_id'), 'disputes', ['order_id'], unique=False)
    op.create_index(op.f('ix_disputes_status'), 'disputes', ['status'], unique=False)
    op.create_index(op.f('ix_disputes_user_id'), 'disputes', ['user_id'], unique=False)
    op.create_table('job_offers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('duration_text', sa.String(length=200), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'accepted', 'rejected', 'withdrawn', name='offerstatus'), nullable=False),
    sa.Column('is_seen', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job_posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'provider_id', name='uq_job_offer_once')
    )
    op.create_index(op.f('ix_job_offers_job_id'), 'job_offers', ['job_id'], unique=False)
    op.create_index(op.f('ix_job_offers_provider_id'), 'job_offers', ['provider_id'], unique=False)
    op.create_index(op.f('ix_job_offers_status'), 'job_offers', ['status'], unique=False)
    op.create_table('order_checkins',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('side', sa.Enum('user', 'provider', name='checkinside'), nullable=False),
    sa.Column('response', sa.Enum('arrived', 'delayed', 'cant_come', 'no_show', name='checkinresponse'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_checkins_order_id'), 'order_checkins', ['order_id'], unique=False)
    op.add_column('categories', sa.Column('lead_fee', sa.Float(), nullable=True))
    op.add_column('orders', sa.Column('booking_mode', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_orders_created_at'), 'orders', ['created_at'], unique=False)
    op.create_index(op.f('ix_orders_date'), 'orders', ['date'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.add_column('providers', sa.Column('is_paused', sa.Boolean(), nullable=False))
    op.add_column('providers', sa.Column('is_verified', sa.Boolean(), nullable=False))
    op.add_column('providers', sa.Column('is_blocked', sa.Boolean(), nullable=False))
    op.add_column('providers', sa.Column('owner_user_id', sa.Integer(), nullable=True))
    op.add_column('providers', sa.Column('balance', sa.Float(), nullable=False))
    op.add_column('providers', sa.Column('lead_fee', sa.Float(), nullable=True))
    op.add_column('providers', sa.Column('completed_orders_count', sa.Integer(), nullable=False))
    op.add_column('providers', sa.Column('cancelled_orders_count', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_providers_owner_user_id'), 'providers', ['owner_user_id'], unique=False)
    op.create_foreign_key(None, 'providers', 'users', ['owner_user_id'], ['id'])
    op.add_column('transactions', sa.Column('provider_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_transactions_provider_id'), 'transactions', ['provider_id'], unique=False)
    op.create_foreign_key(None, 'transactions', 'providers', ['provider_id'], ['id'], ondelete='SET NULL')
    op.add_column('users', sa.Column('premium_until', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('is_super_admin', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('admin_role_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('reminder_offset_minutes', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('finance_group_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_finance_group_id'), 'users', ['finance_group_id'], unique=False)
    op.create_foreign_key(None, 'users', 'finance_groups', ['finance_group_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'users', 'admin_roles', ['admin_role_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_finance_group_id'), table_name='users')
    op.drop_column('users', 'finance_group_id')
    op.drop_column('users', 'reminder_offset_minutes')
    op.drop_column('users', 'admin_role_id')
    op.drop_column('users', 'is_super_admin')
    op.drop_column('users', 'premium_until')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_index(op.f('ix_transactions_provider_id'), table_name='transactions')
    op.drop_column('transactions', 'provider_id')
    op.drop_constraint(None, 'providers', type_='foreignkey')
    op.drop_index(op.f('ix_providers_owner_user_id'), table_name='providers')
    op.drop_column('providers', 'cancelled_orders_count')
    op.drop_column('providers', 'completed_orders_count')
    op.drop_column('providers', 'lead_fee')
    op.drop_column('providers', 'balance')
    op.drop_column('providers', 'owner_user_id')
    op.drop_column('providers', 'is_blocked')
    op.drop_column('providers', 'is_verified')
    op.drop_column('providers', 'is_paused')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_date'), table_name='orders')
    op.drop_index(op.f('ix_orders_created_at'), table_name='orders')
    op.drop_column('orders', 'booking_mode')
    op.drop_column('categories', 'lead_fee')
    op.drop_index(op.f('ix_order_checkins_order_id'), table_name='order_checkins')
    op.drop_table('order_checkins')
    op.drop_index(op.f('ix_job_offers_status'), table_name='job_offers')
    op.drop_index(op.f('ix_job_offers_provider_id'), table_name='job_offers')
    op.drop_index(op.f('ix_job_offers_job_id'), table_name='job_offers')
    op.drop_table('job_offers')
    op.drop_index(op.f('ix_disputes_user_id'), table_name='disputes')
    op.drop_index(op.f('ix_disputes_status'), table_name='disputes')
    op.drop_index(op.f('ix_disputes_order_id'), table_name='disputes')
    op.drop_index(op.f('ix_disputes_created_at'), table_name='disputes')
    op.drop_table('disputes')
    op.drop_index('ix_dm_recipient_unread', table_name='direct_messages')
    op.drop_index('ix_dm_pair', table_name='direct_messages')
    op.drop_index(op.f('ix_direct_messages_sender_id'), table_name='direct_messages')
    op.drop_index(op.f('ix_direct_messages_recipient_id'), table_name='direct_messages')
    op.drop_index(op.f('ix_direct_messages_job_id'), table_name='direct_messages')
    op.drop_index(op.f('ix_direct_messages_created_at'), table_name='direct_messages')
    op.drop_table('direct_messages')
    op.drop_index(op.f('ix_call_deals_status'), table_name='call_deals')
    op.drop_index(op.f('ix_call_deals_provider_user_id'), table_name='call_deals')
    op.drop_index(op.f('ix_call_deals_created_at'), table_name='call_deals')
    op.drop_index(op.f('ix_call_deals_client_id'), table_name='call_deals')
    op.drop_index(op.f('ix_call_deals_call_id'), table_name='call_deals')
    op.drop_table('call_deals')
    op.drop_index(op.f('ix_workout_logs_user_id'), table_name='workout_logs')
    op.drop_index(op.f('ix_workout_logs_date'), table_name='workout_logs')
    op.drop_table('workout_logs')
    op.drop_index(op.f('ix_support_messages_ticket_id'), table_name='support_messages')
    op.drop_index(op.f('ix_support_messages_created_at'), table_name='support_messages')
    op.drop_table('support_messages')
    op.drop_index(op.f('ix_provider_fraud_stats_provider_id'), table_name='provider_fraud_stats')
    op.drop_index(op.f('ix_provider_fraud_stats_month'), table_name='provider_fraud_stats')
    op.drop_table('provider_fraud_stats')
    op.drop_index(op.f('ix_provider_blocked_times_provider_id'), table_name='provider_blocked_times')
    op.drop_table('provider_blocked_times')
    op.drop_index(op.f('ix_listing_photos_listing_id'), table_name='listing_photos')
    op.drop_table('listing_photos')
    op.drop_index(op.f('ix_job_posts_user_id'), table_name='job_posts')
    op.drop_index(op.f('ix_job_posts_status'), table_name='job_posts')
    op.drop_index(op.f('ix_job_posts_expires_at'), table_name='job_posts')
    op.drop_index(op.f('ix_job_posts_created_at'), table_name='job_posts')
    op.drop_index(op.f('ix_job_posts_category_id'), table_name='job_posts')
    op.drop_index(op.f('ix_job_posts_assigned_provider_id'), table_name='job_posts')
    op.drop_table('job_posts')
    op.drop_index(op.f('ix_campaign_votes_user_id'), table_name='campaign_votes')
    op.drop_index(op.f('ix_campaign_votes_provider_id'), table_name='campaign_votes')
    op.drop_index(op.f('ix_campaign_votes_campaign_id'), table_name='campaign_votes')
    op.drop_table('campaign_votes')
    op.drop_index(op.f('ix_call_history_receiver_id'), table_name='call_history')
    op.drop_index(op.f('ix_call_history_provider_id'), table_name='call_history')
    op.drop_index(op.f('ix_call_history_caller_id'), table_name='call_history')
    op.drop_table('call_history')
    op.drop_index(op.f('ix_blocked_users_user_id'), table_name='blocked_users')
    op.drop_index(op.f('ix_blocked_users_provider_id'), table_name='blocked_users')
    op.drop_table('blocked_users')
    op.drop_index(op.f('ix_alarm_logs_user_id'), table_name='alarm_logs')
    op.drop_index(op.f('ix_alarm_logs_fired_at'), table_name='alarm_logs')
    op.drop_index(op.f('ix_alarm_logs_alarm_id'), table_name='alarm_logs')
    op.drop_table('alarm_logs')
    op.drop_index(op.f('ix_workout_plans_user_id'), table_name='workout_plans')
    op.drop_table('workout_plans')
    op.drop_index(op.f('ix_todos_user_id'), table_name='todos')
    op.drop_table('todos')
    op.drop_index(op.f('ix_support_tickets_user_id'), table_name='support_tickets')
    op.drop_index(op.f('ix_support_tickets_status'), table_name='support_tickets')
    op.drop_index(op.f('ix_support_tickets_last_message_at'), table_name='support_tickets')
    op.drop_index(op.f('ix_support_tickets_created_at'), table_name='support_tickets')
    op.drop_table('support_tickets')
    op.drop_index(op.f('ix_shopping_lists_user_id'), table_name='shopping_lists')
    op.drop_table('shopping_lists')
    op.drop_index(op.f('ix_product_price_entries_product_id'), table_name='product_price_entries')
    op.drop_table('product_price_entries')
    op.drop_index(op.f('ix_premium_payments_user_id'), table_name='premium_payments')
    op.drop_index(op.f('ix_premium_payments_status'), table_name='premium_payments')
    op.drop_index(op.f('ix_premium_payments_created_at'), table_name='premium_payments')
    op.drop_table('premium_payments')
    op.drop_index(op.f('ix_plans_user_id'), table_name='plans')
    op.drop_table('plans')
    op.drop_index(op.f('ix_planned_payments_user_id'), table_name='planned_payments')
    op.drop_table('planned_payments')
    op.drop_index(op.f('ix_nutrition_profiles_user_id'), table_name='nutrition_profiles')
    op.drop_table('nutrition_profiles')
    op.drop_index(op.f('ix_meal_logs_user_id'), table_name='meal_logs')
    op.drop_index(op.f('ix_meal_logs_logged_at'), table_name='meal_logs')
    op.drop_table('meal_logs')
    op.drop_index(op.f('ix_listings_user_id'), table_name='listings')
    op.drop_index(op.f('ix_listings_status'), table_name='listings')
    op.drop_index(op.f('ix_listings_expires_at'), table_name='listings')
    op.drop_index(op.f('ix_listings_category_key'), table_name='listings')
    op.drop_table('listings')
    op.drop_index(op.f('ix_finance_records_user_id'), table_name='finance_records')
    op.drop_table('finance_records')
    op.drop_index('ix_device_tokens_user_id_token', table_name='device_tokens')
    op.drop_index(op.f('ix_device_tokens_user_id'), table_name='device_tokens')
    op.drop_index(op.f('ix_device_tokens_token'), table_name='device_tokens')
    op.drop_index(op.f('ix_device_tokens_id'), table_name='device_tokens')
    op.drop_table('device_tokens')
    op.drop_index(op.f('ix_daily_activity_user_id'), table_name='daily_activity')
    op.drop_index(op.f('ix_daily_activity_date'), table_name='daily_activity')
    op.drop_table('daily_activity')
    op.drop_index(op.f('ix_campaigns_starts_at'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_is_active'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_ends_at'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_category_id'), table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index(op.f('ix_audit_logs_section'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_admin_user_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_alarms_user_id'), table_name='alarms')
    op.drop_table('alarms')
    op.drop_table('promos')
    op.drop_index(op.f('ix_product_catalog_name'), table_name='product_catalog')
    op.drop_table('product_catalog')
    op.drop_index(op.f('ix_finance_groups_owner_id'), table_name='finance_groups')
    op.drop_index(op.f('ix_finance_groups_invite_code'), table_name='finance_groups')
    op.drop_table('finance_groups')
    op.drop_index(op.f('ix_exercises_target'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_name_uz'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_external_id'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_equipment'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_category'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_body_part'), table_name='exercises')
    op.drop_table('exercises')
    op.drop_index(op.f('ix_admin_roles_name'), table_name='admin_roles')
    op.drop_table('admin_roles')
    # ### end Alembic commands ###
