"""add search indexes: trigram, partial, pending plans

Revision ID: ece5f1b1b853
Revises: 6b2478ceb5c8
Create Date: 2026-09-06 07:57:38.074826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by alembic.
revision: str = 'ece5f1b1b853'
down_revision: Union[str, None] = '6b2478ceb5c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # `gin_trgm_ops` shu kengaytmasiz mavjud emas — indekslardan OLDIN.
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")

    # DIQQAT (katta ishchi baza uchun): `CREATE INDEX` yozuvni bloklaydi.
    # Jadval yirik bo'lsa migratsiyani ishlatmang, indekslarni qo'lda
    # `CREATE INDEX CONCURRENTLY` bilan yarating (u tranzaksiyadan tashqarida
    # ishlaydi, shuning uchun bu yerga qo'yib bo'lmaydi), keyin
    # `alembic stamp ece5f1b1b853` qiling.
    op.create_index('ix_listings_active_cat_created', 'listings', ['category_key', 'created_at', 'id'], unique=False, postgresql_where=sa.text("status = 'active'"))
    op.create_index('ix_listings_active_created', 'listings', ['created_at', 'id'], unique=False, postgresql_where=sa.text("status = 'active'"))
    op.create_index('ix_listings_active_geo', 'listings', ['lat', 'lng'], unique=False, postgresql_where=sa.text("status = 'active'"))
    op.create_index('ix_listings_description_trgm', 'listings', ['description'], unique=False, postgresql_using='gin', postgresql_ops={'description': 'gin_trgm_ops'})
    op.create_index('ix_listings_title_trgm', 'listings', ['title'], unique=False, postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    op.create_index('ix_plans_pending_due', 'plans', ['due_date'], unique=False, postgresql_where=sa.text('is_completed = false AND is_notified = false'))
    op.create_index('ix_providers_active_rating', 'providers', ['rating', 'id'], unique=False, postgresql_where=sa.text('is_active'))
    op.create_index('ix_providers_address_trgm', 'providers', ['address'], unique=False, postgresql_using='gin', postgresql_ops={'address': 'gin_trgm_ops'})
    op.create_index('ix_providers_name_trgm', 'providers', ['name'], unique=False, postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_providers_name_trgm', table_name='providers', postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.drop_index('ix_providers_address_trgm', table_name='providers', postgresql_using='gin', postgresql_ops={'address': 'gin_trgm_ops'})
    op.drop_index('ix_providers_active_rating', table_name='providers', postgresql_where=sa.text('is_active'))
    op.drop_index('ix_plans_pending_due', table_name='plans', postgresql_where=sa.text('is_completed = false AND is_notified = false'))
    op.drop_index('ix_listings_title_trgm', table_name='listings', postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    op.drop_index('ix_listings_description_trgm', table_name='listings', postgresql_using='gin', postgresql_ops={'description': 'gin_trgm_ops'})
    op.drop_index('ix_listings_active_geo', table_name='listings', postgresql_where=sa.text("status = 'active'"))
    op.drop_index('ix_listings_active_created', table_name='listings', postgresql_where=sa.text("status = 'active'"))
    op.drop_index('ix_listings_active_cat_created', table_name='listings', postgresql_where=sa.text("status = 'active'"))
    # ### end Alembic commands ###
