CATEGORIES_DATA = [
    {
        "key": "sartarosh",
        "title_uz": "Sartarosh",
        "subtitle_uz": "Yaqin atrofdagi sartaroshlar va band qilish",
        "icon": "scissors",
        "accent_color": "#2196F3",
        "variants": [
            {"label_uz": "Erkaklar kesimi", "base_price": 50000},
            {"label_uz": "Soqol olish", "base_price": 25000},
            {"label_uz": "Bolalar kesimi", "base_price": 35000},
            {"label_uz": "Styling", "base_price": 60000},
        ],
    },
    {
        "key": "salon",
        "title_uz": "Salon",
        "subtitle_uz": "Salonda vaqt bron qilish",
        "icon": "sparkles",
        "accent_color": "#E91E63",
        "variants": [
            {"label_uz": "Manikyur", "base_price": 70000},
            {"label_uz": "Pedikyur", "base_price": 90000},
            {"label_uz": "Soch turmagi", "base_price": 80000},
            {"label_uz": "Make-up", "base_price": 150000},
        ],
    },
    {
        "key": "futbol",
        "title_uz": "Futbol",
        "subtitle_uz": "Futbol maydonini band qilish",
        "icon": "trophy",
        "accent_color": "#4CAF50",
        "variants": [
            {"label_uz": "1 soat (kichik maydon)", "base_price": 200000},
            {"label_uz": "1 soat (katta maydon)", "base_price": 350000},
            {"label_uz": "2 soat (kichik maydon)", "base_price": 380000},
            {"label_uz": "2 soat (katta maydon)", "base_price": 650000},
        ],
    },
    {
        "key": "ishchi",
        "title_uz": "Ishchi",
        "subtitle_uz": "Ishchi yollash va kunlik ishlar",
        "icon": "users",
        "accent_color": "#FF9800",
        "variants": [
            {"label_uz": "Yuk kotoruvchi (1 kishi)", "base_price": 150000},
            {"label_uz": "Yuk kotoruvchi (2 kishi)", "base_price": 280000},
            {"label_uz": "Qora ish - 4 soat", "base_price": 200000},
            {"label_uz": "Qora ish - kunlik", "base_price": 400000},
        ],
    },
    {
        "key": "usta",
        "title_uz": "Usta",
        "subtitle_uz": "Usta chaqirish va tamlash",
        "icon": "wrench",
        "accent_color": "#009688",
        "variants": [
            {"label_uz": "Mebel yigish", "base_price": 150000},
            {"label_uz": "Eshik/oyna tamiri", "base_price": 120000},
            {"label_uz": "Devorga osish/biriktirish", "base_price": 80000},
            {"label_uz": "Boshqa tamlash", "base_price": 100000},
        ],
    },
    {
        "key": "elektrik",
        "title_uz": "Elektrik",
        "subtitle_uz": "Elektr montaj va favqulodda chaqiruv",
        "icon": "zap",
        "accent_color": "#D97706",
        "variants": [
            {"label_uz": "Rozetka/lyustra montaj", "base_price": 100000},
            {"label_uz": "Simlash", "base_price": 250000},
            {"label_uz": "Shoshilinch chaqiruv", "base_price": 200000},
            {"label_uz": "Uy elektr tekshiruvi", "base_price": 180000},
        ],
    },
    {
        "key": "santexnik",
        "title_uz": "Santexnik",
        "subtitle_uz": "Santexnik va suv oqimi",
        "icon": "droplets",
        "accent_color": "#03A9F4",
        "variants": [
            {"label_uz": "Smesitel almashtirish", "base_price": 120000},
            {"label_uz": "Toshma/probka tozalash", "base_price": 150000},
            {"label_uz": "Quvur ulash", "base_price": 200000},
            {"label_uz": "Shoshilinch chaqiruv", "base_price": 250000},
        ],
    },
    {
        "key": "tozalash",
        "title_uz": "Tozalash",
        "subtitle_uz": "Uy yoki ofis tozalash xizmati",
        "icon": "sprayCan",
        "accent_color": "#00BCD4",
        "variants": [
            {"label_uz": "1 xonali kvartira", "base_price": 200000},
            {"label_uz": "2 xonali kvartira", "base_price": 320000},
            {"label_uz": "3 xonali kvartira", "base_price": 450000},
            {"label_uz": "Ofis (50 m²)", "base_price": 400000},
        ],
    },
    {
        "key": "avtoYordam",
        "title_uz": "Avto-yordam",
        "subtitle_uz": "Evakuator, akkumulyator, yol yordami",
        "icon": "car",
        "accent_color": "#FF5722",
        "variants": [
            {"label_uz": "Evakuator", "base_price": 250000},
            {"label_uz": "Akkumulyator quvvatlash", "base_price": 80000},
            {"label_uz": "Shinopola (1 gildirak)", "base_price": 70000},
            {"label_uz": "Yol ustasi", "base_price": 150000},
        ],
    },
    {
        "key": "konditsioner",
        "title_uz": "Konditsioner",
        "subtitle_uz": "Konditsioner montaj va profilaktika",
        "icon": "wind",
        "accent_color": "#3F51B5",
        "variants": [
            {"label_uz": "Montaj", "base_price": 600000},
            {"label_uz": "Demontaj", "base_price": 250000},
            {"label_uz": "Profilaktika tozalash", "base_price": 180000},
            {"label_uz": "Gaz toldirish", "base_price": 350000},
        ],
    },
    {
        "key": "enaga",
        "title_uz": "Enaga",
        "subtitle_uz": "Bola qarovchi va enaga",
        "icon": "baby",
        "accent_color": "#9C27B0",
        "variants": [
            {"label_uz": "Soatlik (3 soat)", "base_price": 120000},
            {"label_uz": "Yarim kun (5 soat)", "base_price": 200000},
            {"label_uz": "Toliq kun (10 soat)", "base_price": 380000},
            {"label_uz": "Tunda (8 soat)", "base_price": 350000},
        ],
    },
    {
        "key": "repetitor",
        "title_uz": "Repetitor",
        "subtitle_uz": "Repetitor va oqituvchi xizmati",
        "icon": "bookOpen",
        "accent_color": "#673AB7",
        "variants": [
            {"label_uz": "Matematika (1 dars)", "base_price": 120000},
            {"label_uz": "Ingliz tili (1 dars)", "base_price": 100000},
            {"label_uz": "Fizika (1 dars)", "base_price": 130000},
            {"label_uz": "Test tayyorlov (1 dars)", "base_price": 150000},
        ],
    },
    {
        "key": "dezinfeksiya",
        "title_uz": "Dezinfeksiya",
        "subtitle_uz": "Uy, ofis va mashina dezinfeksiyasi",
        "icon": "shieldCheck",
        "accent_color": "#10B981",
        "variants": [
            {"label_uz": "Kvartira dezinfeksiyasi", "base_price": 150000},
            {"label_uz": "Ofis dezinfeksiyasi", "base_price": 250000},
            {"label_uz": "Mashina dezinfeksiyasi", "base_price": 100000},
            {"label_uz": "Maktab/bogcha", "base_price": 400000},
        ],
    },
    {
        "key": "texnikaUstasi",
        "title_uz": "Texnika ustasi",
        "subtitle_uz": "Kir yuvish, muzlatgich, TV tamlash",
        "icon": "monitor",
        "accent_color": "#607D8B",
        "variants": [
            {"label_uz": "Kir yuvish mashinasi", "base_price": 150000},
            {"label_uz": "Muzlatgich tamlash", "base_price": 180000},
            {"label_uz": "Televizor tamlash", "base_price": 120000},
            {"label_uz": "Mikroto`lqinli pech", "base_price": 80000},
        ],
    },
    {
        "key": "kuryerlik",
        "title_uz": "Kuryerlik",
        "subtitle_uz": "Hujjat va sovgalarni tezkor yetkazish",
        "icon": "bike",
        "accent_color": "#FFC107",
        "variants": [
            {"label_uz": "Hujjat yetkazish", "base_price": 30000},
            {"label_uz": "Sovga yetkazish", "base_price": 50000},
            {"label_uz": "Kichik yuk (5 kg)", "base_price": 40000},
            {"label_uz": "Katta yuk (20 kg)", "base_price": 80000},
        ],
    },
    {
        "key": "massajHijoma",
        "title_uz": "Massaj va Hijoma",
        "subtitle_uz": "Massaj va Hijoma xizmatlari",
        "icon": "hand",
        "accent_color": "#795548",
        "variants": [
            {"label_uz": "Massaj (60 daqiqa)", "base_price": 150000},
            {"label_uz": "Hijoma (erkaklar)", "base_price": 200000},
            {"label_uz": "Hijoma (ayollar)", "base_price": 200000},
            {"label_uz": "Spa paket", "base_price": 350000},
        ],
    },
    {
        "key": "hamshira",
        "title_uz": "Hamshira",
        "subtitle_uz": "Uyga hamshira chaqirish",
        "icon": "heartPulse",
        "accent_color": "#FF5252",
        "variants": [
            {"label_uz": "Uyga hamshira (3 soat)", "base_price": 100000},
            {"label_uz": "In`ektsiya", "base_price": 30000},
            {"label_uz": "Qon tahlili (uyda)", "base_price": 120000},
            {"label_uz": "Tun bo`yi hamshira", "base_price": 300000},
        ],
    },
    {
        "key": "tadbirlar",
        "title_uz": "Tadbirlar",
        "subtitle_uz": "Tadbirlar, marosimlar va dam olish joylari",
        "icon": "partyPopper",
        "accent_color": "#E91E63",
        "variants": [
            {"label_uz": "Toy rejissyor", "base_price": 2000000},
            {"label_uz": "Tug`ilgan kun", "base_price": 500000},
            {"label_uz": "Dam olish joyi bron", "base_price": 300000},
            {"label_uz": "Korporativ tadbir", "base_price": 1500005},
        ],
    },
    {
        "key": "yana",
        "title_uz": "Yana xizmatlar",
        "subtitle_uz": "Boshqa xizmatlar va yordam",
        "icon": "moreHorizontal",
        "accent_color": "#90A4AE",
        "variants": [
            {"label_uz": "Boshqa xizmat", "base_price": 100000},
        ],
    },
]
